### ISSUE TITLE
`.code-highlighter-cache` folder not automatically created.

### ISSUE THREAD

**Issue by pbendersky** [octopress/code-highlighter#6] opened 2015-05-20 14:38 UTC
Steps to reproduce:
1. Create a new site using `octoprsess new site`
2. Add `octopress-genesis-theme`
3. Try to serve it, and be greeted with this error:

```
/Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/find.rb:40:in `block in find': No such file or directory (Errno::ENOENT)
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/find.rb:40:in `collect!'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/find.rb:40:in `find'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `each'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `to_a'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/cache.rb:41:in `clean'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-code-highlighter-4.2.4/lib/octopress-code-highlighter/hooks.rb:13:in `post_write'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:223:in `block in write'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `each'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `write'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:53:in `process'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/bin/jekyll:23:in `load'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/bin/jekyll:23:in `<main>'
```

Workaround: manually create the `.code-highlighter-cache` folder, and site generation works as expected.

**Comment by imathis** [comment] 2015-05-21 05:06
I'm sorry about that. I'll work on a fix.

**Comment by imathis** [comment] 2015-05-23 04:47
I've tried to reproduce this and I can't seem to. Your steps don't include any gems other than the genesis theme. Obviously you have code-highlighter as well. I've tried creating a bare site, adding the genesis theme, and adding code snippets and the `octopress-codefence` gem, and it seems to create the `.code-highlighter-cache` directory just fine.

**Comment by imathis** [comment] 2015-05-26 03:10
I'm closing this issue because I do not believe this to be a problem from what I can tell. If you can give me some reliable way to reproduce this bug I'll reopen and work on this again.

**Closed** 2015-05-26 03:09 UTC

**Comment by pbendersky** [comment] 2015-05-26 11:37
Thank you for looking. I'll re-open if I can reproduce it.
